"""Export a saved test as Playwright (pytest) code or a Gherkin feature."""
from __future__ import annotations

import re

from .browser import PLACEHOLDER


def _py(s: str) -> str:
    return repr(s)


def _val(s: str) -> str:
    """Step value as a Python expression; credentials come from the environment."""
    parts = []
    for i, chunk in enumerate(PLACEHOLDER.split(s)):
        if i % 2:
            parts.append(f'os.environ["TESTGEN_{chunk.upper()}"]')
        elif chunk:
            parts.append(_py(chunk))
    return " + ".join(parts) or "''"


def _locator_expr(locator: list[dict]) -> str:
    if not locator:
        return "page.locator('body')"
    c = locator[0]
    k = c["kind"]
    if k == "testid":
        return f"page.get_by_test_id({_py(c['value'])})"
    if k == "role":
        return f"page.get_by_role({_py(c['role'])}, name={_py(c['name'])}, exact=True)"
    if k == "label":
        return f"page.get_by_label({_py(c['value'])}, exact=True)"
    if k == "placeholder":
        return f"page.get_by_placeholder({_py(c['value'])}, exact=True)"
    if k == "text":
        return f"page.get_by_text({_py(c['value'])}, exact=True)"
    return f"page.locator({_py(c['value'])})"


def to_playwright(test: dict) -> str:
    fn = re.sub(r"\W+", "_", test["name"].lower()).strip("_") or "generated"
    out = [
        '"""Generated by AI Test Generator.',
        f"Scenario: {test.get('scenario', '')}",
        '"""',
        "import os",
        "import re",
        "",
        "from playwright.sync_api import Page, expect",
        "",
        "",
        f"def test_{fn}(page: Page) -> None:",
    ]
    for s in test["steps"]:
        out.append(f"    # {s['description']}")
        loc = _locator_expr(s.get("locator", []))
        v = s.get("value", "")
        a = s["action"]
        if a == "navigate":
            out.append(f"    page.goto({_py(v)})")
        elif a == "click":
            out.append(f"    {loc}.first.click()")
        elif a == "fill":
            out.append(f"    {loc}.first.fill({_val(v)})")
            if s.get("press_enter"):
                out.append(f"    {loc}.first.press('Enter')")
        elif a == "select_option":
            out.append(f"    {loc}.first.select_option(label={_val(v)})")
        elif a == "hover":
            out.append(f"    {loc}.first.hover()")
        elif a == "press_key":
            out.append(f"    page.keyboard.press({_py(v)})")
        elif a == "scroll":
            out.append(f"    page.mouse.wheel(0, {-700 if v == 'up' else 700})")
        elif a == "wait":
            out.append(f"    page.wait_for_timeout({int(float(v or 1) * 1000)})")
        elif a == "assert_visible":
            out.append(f"    expect({loc}.first).to_be_visible()")
        elif a == "assert_text_present":
            out.append(f"    expect(page.get_by_text({_val(v)}).first).to_be_visible()")
        elif a == "assert_url_contains":
            out.append(f"    expect(page).to_have_url(re.compile(re.escape({_val(v)})))")
    return "\n".join(out) + "\n"


def to_gherkin(test: dict) -> str:
    lines = [f"Feature: {test.get('project', 'Web application')}", "",
             f"  Scenario: {test['name']}"]
    if test.get("scenario"):
        lines.insert(1, f"  {test['scenario']}")
    prev = None
    for i, s in enumerate(test["steps"]):
        kind = "Given" if i == 0 else "Then" if s["action"].startswith("assert") else "When"
        lines.append(f"    {'And' if kind == prev else kind} {s['description']}")
        prev = kind
    return "\n".join(lines) + "\n"
